source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'SocialIntuition' do

    pod 'EVReflection/MoyaRxSwift'
    pod 'Alamofire'
    pod 'SwiftSpinner'

    target "SocialIntuitionTests" do
        inherit! :search_paths
        #        pod 'OCMock', '~> 2.0.1'
    end
end
